#!/bin/sh
#
# Start adb....
#
case "$1" in
  start)
        killall adbd

        if [ ! -f "/data/disableadb"  ];then
                echo "Starting adb ..."
                # echo -n $adb_dev > demo/strings/0x409/serialnumber
                adbd &
                sleep 1
        else
                echo "Not start adb"
        fi
        ;;
  stop)
        killall adbd
        sleep 1
        ;;
  restart|reload)
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
