#!/bin/sh
# usb_init script
#! /bin/sh

case "$1" in
  start)
    #wait for telephony ready
    #sleep 5
    #Enable USB configurations
    echo 0 > /sys/class/android_usb/android0/enable
    echo 2ecc > /sys/class/android_usb/android0/idVendor
    echo 3012 > /sys/class/android_usb/android0/idProduct
    echo 0100 > /sys/class/android_usb/android0/bcdDevice
    echo Asrmicro > /sys/class/android_usb/android0/iManufacturer
    echo 123456789ABCD > /sys/class/android_usb/android0/iSerial

    # iProduct will displayed on Windows
    echo Asrmicro > /sys/class/android_usb/android0/iProduct
    # store function in node functions if os detect is not compiled,
    # otherwise the functions are stored in win7/win8/apple
    echo rndis,acm,marvell_diag,marvell_debug,adb > /sys/class/android_usb/android0/functions
    echo rndis,acm,marvell_diag,marvell_debug,adb > /sys/class/android_usb/android0/win7
    echo rndis,acm,marvell_diag,marvell_debug,adb > /sys/class/android_usb/android0/win8
    echo rndis,acm,marvell_diag,marvell_debug,adb > /sys/class/android_usb/android0/olinux
    echo ecm > /sys/class/android_usb/android0/apple

    #below items are for enumeraton stage2
    echo rndis,acm,marvell_diag,marvell_debug > /sys/class/android_usb/android0/win7_s2
    echo rndis,acm,marvell_diag,marvell_debug > /sys/class/android_usb/android0/win8_s2
    echo rndis,acm,marvell_diag,marvell_debug > /sys/class/android_usb/android0/olinux_s2
    echo ecm > /sys/class/android_usb/android0/apple_s2
    echo win7 > /sys/class/android_usb/android0/os
    echo 239 > /sys/class/android_usb/android0/bDeviceClass
    echo Asrmicro > /sys/class/android_usb/android0/f_rndis/manufacturer
    echo 0bb4 > /sys/class/android_usb/android0/f_rndis/vendorID
    echo 1 > /sys/class/android_usb/android0/f_rndis/wceis
    echo 1 > /sys/class/android_usb/android0/f_acm/instances
    echo 1 > /sys/class/android_usb/android0/enable

    #start mbim early to connect with PC, otherwise AT com port will
    #be blocked for tens of seconds
    [ -e /sys/class/android_usb/android0/win8 ] && {
        mbim_enabled=`cat /sys/class/android_usb/android0/win8 | grep mbim`
        if [ -n "$mbim_enabled" ]; then
            /bin/mbim &
        fi
    }
    /etc/init.d/adb $1
    ;;
  stop)
      # echo none > /sys/kernel/config/usb_gadget/demo/UDC
      /etc/init.d/adb $1
      ;;
  *)
      echo "Usage: $0 {start|stop|restart}"
      exit 1
esac

exit $?
